### ISSUE TITLE
BrowserWindow may not refresh the remote html and css in time.

### ISSUE THREAD

**Issue by DrinkingWords** [skpm/sketch-module-web-view#103]
I load a remote html with BrowserWindow like this:
    const BrowserWindow = require('sketch-module-web-view')
    let win = new BrowserWindow({ width: 800, height: 600 })
    win.loadURL('http://sketchcloud.rnd.com/toolbar.html')
After I update the html, the BrowserWindow still load the old html. 
If the html links to a css  file, I can not see the new css style until I reload the BrowserWindow.
Is it because I use 'http', not 'https'？

**Comment by xsfour** [comment]
I'm afraid you have to reload it, because that's how HTTP works

**Comment by xsfour** [comment]
I'm afraid you have to reload it, because that's how HTTP works

**Comment by DrinkingWords** [comment]
Thank you!
