### ISSUE TITLE
Missing Title bar (macOS Catalina Beta)

### ISSUE THREAD

**Issue by rodi01** [skpm/sketch-module-web-view#109]
Using the beta macOS 10.15

I've tried with both my plugin and the sketch-dev-tool plugin. It's missing the title bar and `esc` doesn't close the window. Here is a screenshot:

<img width="830" alt="Screen Shot 2019-06-25 at 6 14 43 PM" src="https://user-images.githubusercontent.com/52461/60143912-5be1c000-9775-11e9-9a14-edbb127c5999.png">

**Comment by WCByrne** [comment]
Seeing this too.🤞it will resolve itself in a future beta.

**Comment by WCByrne** [comment]
Input fields are also not focusable 😞. e.g. the filter input doesn't work in dev tools.

**Comment by mathieudutour** [comment]
It's because of https://github.com/BohemianCoding/SketchAPI/issues/558

**Comment by mathieudutour** [comment]
Closing this in favor of https://github.com/BohemianCoding/SketchAPI/issues/558
