### ISSUE TITLE
Error on Catalina: relativeLevel must be between…

### ISSUE THREAD

**Issue by peerjollux** [skpm/sketch-module-web-view#112]
On Catalina when I try to run the plugin I get the following error:

<img width="831" alt="Screenshot 2019-07-05 at 14 12 06" src="https://user-images.githubusercontent.com/6756753/60721634-e58c4d00-9f2e-11e9-8a10-997319ba687a.png">

**Comment by mathieudutour** [comment]
pretty sure this is the same as https://github.com/skpm/sketch-module-web-view/issues/109
