### ISSUE TITLE
Its confusing that alwaysOnTop isn’t the default

### ISSUE THREAD

**Issue by KevinGutowski** [skpm/sketch-module-web-view#113]
I feel like most plugins will immediately change this (as its confusing to have your window often get lost when unfocusing Sketch). 

These are the steps that led up to my confusion:
1. Run `npm run build` to build the default template code
2. Open sketch
3. Run the plugin
4. Locate the plugin UI window
5. Click on code editor
6. Click back over to sketch
7. Find that you can’t seem to locate the UI window bc its buried underneath some other open windows

**Comment by mathieudutour** [comment]
possibly, but ideally I'd really like to keep the same API, and the same defaults, as the electron module: https://electronjs.org/docs/api/browser-window

**Comment by KevinGutowski** [comment]
I suppose that makes sense. Though I think the electron module is more used in building an app rather than a plugin that goes along with an app? As a user of skpm, having sensible defaults for the context of skpm is more helpful than trying to follow a similar API. I imagine though as a developer it's a bit more manageable when you can keep them to be the same as possible.

**Comment by mathieudutour** [comment]
not only that but it also allows people to leverage all the docs written for Electron which is a lot more fleshed out that for this module 😄
