### ISSUE TITLE
Error when js import setImmediate package

### ISSUE THREAD

**Issue by funfungo** [skpm/sketch-module-web-view#117]
when my webview js file import some modules that have referred the setImmediate.js(https://github.com/YuzuJS/setImmediate) 
there has some error log.
![image](https://user-images.githubusercontent.com/2912182/63270635-2b2c8b80-c2cb-11e9-86f5-4392ced720f7.png)

I checked the setImmediate.js 
![image](https://user-images.githubusercontent.com/2912182/63270738-531bef00-c2cb-11e9-9246-92352ef3fce1.png)
seems like this cause the problem `global.postMessage("", "*");`

so how can i fix this？ setImmediate.js is a very common implementation, so maybe some other will confront this problem too

**Comment by AMoreaux** [comment]
I have this issue too. Did you find a solution @funfungo ?

**Comment by AMoreaux** [comment]
I found a solution with this config in skpm.config.js

```javascript
config.node = isPluginCommand ? false : {
	setImmediate: false, // <---- HERE
};
```

**Comment by vincentmvdm** [comment]
Having this same error right now and it's unfortunately really slowing me down...

Do you have an example of your fix @AMoreaux? My webpack config override does nothing!

**Comment by funfungo** [comment]
> ```js
> setImmediate
> ```
thanks, it works

**Comment by funfungo** [comment]
> I found a solution with this config in skpm.config.js
> 
> ```js
> config.node = isPluginCommand ? false : {
> 	setImmediate: false, // <---- HERE
> };
> ```
thanks, it works

**Comment by funfungo** [comment]
> Having this same error right now and it's unfortunately really slowing me down...
> 
> Do you have an example of your fix @AMoreaux? My webpack config override does nothing!

You can just add it to your webpack config file, it prevent pack setImmediate.js into the bundle js

**Comment by mathieudutour** [comment]
Seems like it's something we should include in the template by default, and add a note about here.

Anybody wants to send a PR?
