### ISSUE TITLE
All production builds using sketch-module-web-view are broken

### ISSUE THREAD

**Issue by jasim** [skpm/sketch-module-web-view#118]
Plugin fails to load with error: 

```
Error: An Obj-C exception occurred.
    at [native code] (/)
    at loadURL (/Users/me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/my-webview-plugin.sketchplugin/Contents/Sketch/main.js:9989:50)
    at /Users/me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/my-webview-plugin.sketchplugin/Contents/Sketch/main.js:9518:24
    at __skpm_run (/Users/me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/my-webview-plugin.sketchplugin/Contents/Sketch/main.js:19521:17)
    at __skpm_run[native code] (/)
  nativeException: (null) is not a file URL
(null)
```

This is a regression due to recent PR https://github.com/skpm/sketch-module-web-view/pull/116. 

This is because `NSURL.URLWithString` returns null if the url contains spaces. The error happens mostly in production builds because of the space in the file path due to the `Application Support` folder.

**Comment by mathieudutour** [comment]
Ah right. Want to send a PR?

**Comment by robintindale** [comment]
`sketch-dev-tools` `0.9.6` doesn't open because of this issue

**Comment by robintindale** [comment]
Looks like fix would be 
```
NSURL.URLWithString(urlString.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLQueryAllowedCharacterSet()))
```

**Comment by jasim** [comment]
Wondering whether `NSURL` allows opening internet urls, and whether that is okay.

**Comment by jasim** [comment]
Wondering whether NSURL allows opening internet urls, and whether that is okay.

**Comment by mathieudutour** [comment]
There is no reason to restrict which url you can open IMO

**Comment by jasim** [comment]
> Ah right. Want to send a PR?

Sorry not for this one.
