### ISSUE TITLE
Programmatically close browserWindow

### ISSUE THREAD

**Issue by FRSgit** [skpm/sketch-module-web-view#123]
Hey, I have a scenario in which I need to close the browser window from different script (and scope) that it was created in. But unfortunately, when I try to fire `.close` method of `BrowserWindow` class, error pops out ;<

I have two sketch commands:

First:
```javascript
import BrowserWindow from 'sketch-module-web-view';

export const webviewIdentifier = 'some.identifier';

export default function () {
  const b = new BrowserWindow({
    identifier: webviewIdentifier,
    width: 800,
    height: 46,
    show: false,
    frame: false,
    alwaysOnTop: true,
    resizable: false,
    acceptsFirstMouse: true
  });

  b.webContents.on('did-finish-load', () => {
    b.show();
  });
}
```

Second:
```javascript
import { getWebview } from 'sketch-module-web-view/remote';
import { webviewIdentifier } from './first';

export default function () {
  const existingWebview = getWebview(webviewIdentifier);
  log(existingWebview);
  if (existingWebview) {
    existingWebview.close();
  }
}
```

So I'm running first command and then the second. `existingWebview`logs okay (I get the browserWindow object, which has the close command) but when script runs `existingWebview.close();`, error like this is being logged to the console:
```
Possible Unhandled Promise Rejection:
>TypeError: undefined is not an object (evaluating 'panel.delegate().utils.parentWindow')
close browser-api.js:55:0
_callee$ config_ui.js:63:12
c auth-box.umd.js:1:17598
auth-box.umd.js:1:17400
asyncGeneratorStep config_ui.js:14514:103
_next config_ui.js:14516:212
index.js:79:0
timeout.js:18:0
```

I tried to look into sketch-module-web-view code, but unfortunately I've never worked with anything appkit related (or obj-c, cocoascript, actually anything different than frontend stuff) and I have no idea what could be wron.
Does anybody know how to overcome this problem?

**Comment by mathieudutour** [comment]
should be fixed in 3.2.0
