### ISSUE TITLE
Area in top of window is not interactable and covers web content.

### ISSUE THREAD

**Issue by sclausendk** [skpm/sketch-module-web-view#125]
There is an invisible area in the top of the window that covers the web content, so it is not interactable. Buttons and draggable does not work in this area.

Approx. area:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/32878631/65371655-16df0400-dc66-11e9-89a9-9b28993a7143.png">

**Comment by mathieudutour** [comment]
that's weird hahaha.
Do you have a repro somewhere?

**Comment by sclausendk** [comment]
Yes, very weird 🤔
I just added you to my repo: https://github.com/sclausendk/color-systems/invitations

**Comment by mathieudutour** [comment]
I can repro but I have no idea what's happening. I'll try to think about it

**Comment by lpsBetty** [comment]
ah that's why, I added a button in the center on the top of a frameless window, and i can't really click it.. i couldn't found out why, and when i moved it to the right it was clickable - the problem described here seems like the only explanation 😅

**Comment by robintindale** [comment]
I guess it's like the equivalent of where the window title would be. There may be some hack like setting it to blank or force removing it, if that's the case. Just a guess though 🤷‍♂️

**Comment by mathieudutour** [comment]
Spot on! Didn't think about that.

Should be fixed in 3.2.2

**Comment by robintindale** [comment]
woo :) good guess
