### ISSUE TITLE
Makes Sketch Crash on Mac OS Catalina

### ISSUE THREAD

**Issue by sclausendk** [skpm/sketch-module-web-view#126]
Title says it all.

**Comment by mathieudutour** [comment]
Well I think there is more to it than just the title...
Do you have a repro somewhere? I’ve been using Catalina for 3 months without issues.

- when do it crash?
- what’s the log?

**Comment by sclausendk** [comment]
I'm sorry. Was a bit tired and frustrated when I wrote this 😄 

I have discovered a few issues:
– "settingsWindow.loadURL(require('./index.html'))" Does not load the file, might be a permission thing? (https://google.com/ works)

– Sketch crashes after I opened and closed the window a few times. (This might be something else than this framework though, still investigating)

**Comment by mathieudutour** [comment]
¯\_(ツ)_/¯ It's working fine on https://github.com/skpm/with-webview. I'd recommend checking what different between your setup and the template
