### ISSUE TITLE
Show as panel/sidebar

### ISSUE THREAD

**Issue by Arjan-Zuidema** [skpm/sketch-module-web-view#128]
How to create a webview as a panel/sidebar instead of a window. I want my plugin to be a part of the UI and not an other window.

**Comment by mathieudutour** [comment]
you can use https://github.com/skpm/sketch-module-web-view/blob/master/docs/browser-window.md#parent-and-child-windows to show the window as a panel

**Comment by Arjan-Zuidema** [comment]
This opens a sheet, not a panel, please re-open.

<img width="1124" alt="Schermafbeelding 2019-10-22 om 09 18 37" src="https://user-images.githubusercontent.com/30040390/67265011-f09ec500-f4ac-11e9-87cc-ba532603db59.png">

**Comment by mathieudutour** [comment]
Well that’s the only 2 options without hooking into the UI of Sketch which is a non-goal of this library.
