### ISSUE TITLE
TypeError: null is not an object (evaluating 'context.plugin.urlForResourceNamed(frameLocation).path')

### ISSUE THREAD

**Issue by bildlich** [skpm/sketch-module-web-view#13]
Using skpm and the example code from the sketch-module-web-view Readme, I get the following error when running my-command:

    TypeError: null is not an object (evaluating 'context.plugin.urlForResourceNamed(frameLocation).path')
    line: 214
    stack: WebUI

    __webpack_require__

    run
    run@[native code]
    column: 70
     «Plugin Output»

Looking at the plugin package, I see that the Resources folder is missing. Maybe that's the reason? How do I add the Resources folder so it gets included to the plugin on build?

**Comment by mathieudutour** [comment]
you can specify `resources` in your package.json: https://github.com/mathieudutour/git-sketch-plugin/blob/master/package.json#L7-L10

**Comment by bildlich** [comment]
Thanks! Now I'm getting:

    🖨  Copied src/manifest.json in 7ms
    error Error while building Resources/test.html
    ./Resources/test.html
    Module parse failed: /Users/xyz/Development/woozle/Resources/test.html Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    | <!DOCTYPE html>
    | <html>
    |   <head>

**Comment by mathieudutour** [comment]
oh my bad, it should only be javascript files in the package.json. just put the html file directly in `myplugin.sketchplugin/Contents/Resources`. You can open an issue on skpm/skpm if you think it would be useful to copy the non-js files specified in the package.json (which I tend to agree)

**Comment by bildlich** [comment]
Still doesn't work. I put `test.html` here: `myplugin.sketchplugin/Contents/Resources` and removed the resources statement from package.json. Build works, but when executing my-command, I get the same error as in the beginning:

    TypeError: null is not an object (evaluating 'context.plugin.urlForResourceNamed(frameLocation).path')
    line: 214
    stack: WebUI

    __webpack_require__

    run
    run@[native code]
    column: 70
     «Plugin Output»

my-command.js looks like this:

    import WebUI from 'sketch-module-web-view'

    const options = {
      identifier: 'unique.id', // to reuse the UI
      x: 0,
      y: 0,
      width: 240,
      height: 180,
      background: NSColor.whiteColor(),
      onlyShowCloseButton: false,
      title: 'My ui',
      hideTitleBar: false,
      shouldKeepAround: true,
      frameLoadDelegate: { // https://developer.apple.com/reference/webkit/webframeloaddelegate?language=objc
        'webView:didFinishLoadForFrame:': function (webView, webFrame) {
          context.document.showMessage('UI loaded!')
          WebUI.clear()
        }
      },
      uiDelegate: {}, // https://developer.apple.com/reference/webkit/webuidelegate?language=objc
      onPanelClose: function () {
        // Stuff
      }
    }

    const webUI = new WebUI(context, 'test.html', options)

**Comment by bildlich** [comment]
It works now. Turns out, Sketch doesn't always reload the script even though I set it up with    

defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES

To reliably reload the script after building, I need to restart Sketch.
