### ISSUE TITLE
Webview stopped working

### ISSUE THREAD

**Issue by jan-dh** [skpm/sketch-module-web-view#135]
The webview stopped working on my [sketch-tailwind plugin](https://github.com/jan-dh/sketch-tailwind) . Did update from Sketch 54 to 60 and updated OS to Catalina. 

Don't see any errors in the web log, Sketch just crashes. I made a branch here if you'd have some time to test?

https://github.com/jan-dh/sketch-tailwind/tree/2.1

**Comment by mathieudutour** [comment]
Update the sketch-module-web-view, you’re way behind

**Comment by jan-dh** [comment]
You're right, updated and everything works again. Thanks!
