### ISSUE TITLE
TypeError: exports[key] is not a function.

### ISSUE THREAD

**Issue by bildlich** [skpm/sketch-module-web-view#14]
On running the plugin I get:

    TypeError: exports[key] is not a function. (In 'exports[key](context)', 'exports[key]' is undefined)
    line: 330
    column: 17

This is my-command.js:

    import WebUI from 'sketch-module-web-view'

    const options = {
      identifier: 'unique.id', // to reuse the UI
      x: 0,
      y: 0,
      width: 240,
      height: 180,
      background: NSColor.whiteColor(),
      onlyShowCloseButton: false,
      title: 'My ui 10',
      hideTitleBar: false,
      shouldKeepAround: true,
      frameLoadDelegate: { // https://developer.apple.com/reference/webkit/webframeloaddelegate?language=objc
        'webView:didFinishLoadForFrame:': function (webView, webFrame) {
          context.document.showMessage('UI loaded!')
          WebUI.clear()
        }
      },
      uiDelegate: {}, // https://developer.apple.com/reference/webkit/webuidelegate?language=objc
      onPanelClose: function () {
        // Stuff
      }
    }

    const webUI = new WebUI(context, 'test.html', options)

**Comment by mathieudutour** [comment]
you need to export the command you want to run:

```js
import WebUI from 'sketch-module-web-view'

export default function (context) {
  const options = {
  identifier: 'unique.id', // to reuse the UI
  x: 0,
  y: 0,
  width: 240,
  height: 180,
  background: NSColor.whiteColor(),
  onlyShowCloseButton: false,
  title: 'My ui 10',
  hideTitleBar: false,
  shouldKeepAround: true,
  frameLoadDelegate: { // https://developer.apple.com/reference/webkit/webframeloaddelegate?language=objc
    'webView:didFinishLoadForFrame:': function (webView, webFrame) {
      context.document.showMessage('UI loaded!')
      WebUI.clear()
    }
  },
  uiDelegate: {}, // https://developer.apple.com/reference/webkit/webuidelegate?language=objc
  onPanelClose: function () {
    // Stuff
  }
}

  const webUI = new WebUI(context, 'test.html', options)
}
```
