### ISSUE TITLE
 How to close Web Content process

### ISSUE THREAD

**Issue by yvanwangl** [skpm/sketch-module-web-view#141]
sketch-module-web-view version is 3.4.1
I use sketch-module-web-view to create a webview  for my sketch plugin when open a document;
When i close document, i execute 
```
browserWindow.close();
browserWindow.destroy();
browserWindow.emit('closed');
```
to close webview; But i find the web content process is still alive in activity monitor.
![active](https://user-images.githubusercontent.com/11405052/71157140-5eccf180-227c-11ea-8002-cb6579a0f07e.png)

**Comment by mathieudutour** [comment]
`browserWindow.close();` should be enough.

It might be because some there are still some async operations that aren't finished. If you try with https://github.com/skpm/sketch-dev-tools, the process is properly cleared when you close the webview
