### ISSUE TITLE
Sending a message to the WebView from your plugin command not working 

### ISSUE THREAD

**Issue by janily** [skpm/sketch-module-web-view#144]
i made a sketch plugin with webview,when sending a message to the WebView from your plugin command,it is not working:
my frotend code is 

```
<script>
      window.a = function() {
        console.log('aaa')
      }
    </script>
```

my plugin code is :

```js
webView.on('did-finish-load', () => {
          console.log('did-finish-load')
          webView.executeJavaScript('a()').then(res => {
            console.log(res)
          })
        })
```

dev tool console is:

![](https://tva1.sinaimg.cn/large/00831rSTgy1gd33xiasjyj30n80b6t9y.jpg)

**Comment by mathieudutour** [comment]
try
```js
webView.executeJavaScript('a()').then(res => {
            console.log(res)
          }).catch(err => console.error(err))
```

and see what's the error

**Comment by janily** [comment]
@mathieudutour  the console.log is null:
![](https://tva1.sinaimg.cn/large/00831rSTgy1gd3lwjd9pqj31a408ijsy.jpg)
my front-end is vue,i put the global funtion in the index.html:

` <script>
      window.a = function() {
        console.log('aaa')
      }
    </script>
`

**Comment by janily** [comment]
@mathieudutour  i try  

`
webView.executeJavaScript('a()').then(res => {
            console.log(res)
          }).catch(err => console.error(err))
`

the console.log is null , **my front is vue, i put the global function in the index.html** "

![](https://tva1.sinaimg.cn/large/00831rSTgy1gd3lwjd9pqj31a408ijsy.jpg)

**Comment by janily** [comment]
@mathieudutour  i have done the issue.sorry, i misunderstanding the about the Sending a message to the plugin from the WebView.close the issue please.

**Comment by codynova** [comment]
@janily Can you please describe what was causing your issue? I believe I'm having the same problem.
