### ISSUE TITLE
async/await does not  work

### ISSUE THREAD

**Issue by jiazhewang** [skpm/sketch-module-web-view#145]
As [this discussion](https://sketchplugins.com/d/1205-guide-how-to-use-async-await-functions-in-your-plugin/7) metioned.

the async/await in my [demo](https://github.com/jiazhewang/sketch-plugin-demos/blob/70d3df2c0d8187dead2f1849348e7b7ed2bd84e8/demos/async-with-react/src/my-command.js#L72) does not work if I did not `npm install @babel/polyfill` and add the code 
```
module.exports = config => {
  config.entry = ['@babel/polyfill', config.entry];
}
```
into `webpack.skpm.config.js`.

After [doing this](https://github.com/jiazhewang/sketch-plugin-demos/blob/70d3df2c0d8187dead2f1849348e7b7ed2bd84e8/demos/async-with-react/webpack.skpm.config.js#L9), it works. However, every time I run the plugin again, the console throws:

> @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.

**Comment by lizheming** [comment]
There has two ways to resolve your problem:

1. install [regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime) as devDependencies and add `import regenerator-runtime` at the first line in your command file.
2. install [@babel/plugin-transform-runtime](https://www.npmjs.com/package/@babel/plugin-transform-runtime) as devDependencies and create `.babelrc` file with following content into root directory of your project:
    ```json
   {
     "plugins": [
       [
         "@babel/plugin-transform-runtime",
         {
           "regenerator": true
         }
       ]
     ]
   }
    ```

I think the second is a good solution and open a pull request skpm/skpm#281 to resolve it. It will work well with default config after the pull request merged.
