### ISSUE TITLE
getURL not working

### ISSUE THREAD

**Issue by stefanb0305** [skpm/sketch-module-web-view#150]
When I execute the following code:
`browserWindow.loadURL(require('../resources/main.html'));`
`console.log("here [0]");`
`console.log(browserWindow.webContents.getURL());`
`console.log("here [1]");`

The output in the console of the Sketch DevTools is only "here [0]"...

Which means that getURL must somehow stop the program from running, right?

**Comment by mathieudutour** [comment]
probably? I never actually used it haha
