### ISSUE TITLE
Typescript types for sketch-module-web-view

### ISSUE THREAD

**Issue by M-Widman-Mesh** [skpm/sketch-module-web-view#153]
- was curious if this repo has an npm package for typescript types? Similar to @sketch-hq/sketch-file-format-ts, but maybe @sketch-hq/sketch-module-web-view-ts?

Thank You!

**Comment by mathieudutour** [comment]
It doesn't - happy to accept a PR to add types to it

**Comment by M-Widman-Mesh** [comment]
@mathieudutour In the coming month or so, I will likely work on strong typing for the browserWindow specifically. I would be willing to share the types declarations, if you are interested!
