### ISSUE TITLE
How to use jQuery in Webview

### ISSUE THREAD

**Issue by brunoming** [skpm/sketch-module-web-view#154]
I tried to import JQuery js file as usual, but it's doesn't work.
Or is there an another way to use jQuery?

**html part**

![image](https://user-images.githubusercontent.com/31105948/89393455-6672d500-d73d-11ea-99eb-57a5376b03eb.png)

**js part**

![image](https://user-images.githubusercontent.com/31105948/89393486-71c60080-d73d-11ea-9d4d-f1c90eef1028.png)

**Comment by lizheming** [comment]
You need move `jquery.js` file to `assets` folder instead of `resources` folder. Then change html src to `../jquery.js`.

`skpm` will compile `.js` files in `resources` folder by webpack. And just copy file in `assets` folder.
