### ISSUE TITLE
How to clear sketch-module-web-view's localStorage

### ISSUE THREAD

**Issue by M-Widman-Mesh** [skpm/sketch-module-web-view#156]
Hello!

I'm having trouble figuring out how to clear the localStorage with use of my sketch-module-web-view. I was wondering if anyone was able to successfully clear their cache.  Not sure if I am missing something but I was unable to find any helpful methods to clear the cache. Any help would be greatly appreciated! Thanks ahead of time!

**Comment by mathieudutour** [comment]
you mean clearing when you don't have a webview opened? I don't think you can. If you do have one open, you can clear it with `localStorage.clear()`

**Comment by M-Widman-Mesh** [comment]
either when it is open or closed, just anyway to clear it in general, but I was able to clear the cache manually with a separate application that I had developed previously to simply clear local storage.
