### ISSUE TITLE
 When switching between themes __skpm-light / __skpm-dark class isn't set correctly

### ISSUE THREAD

**Issue by yaelsch** [skpm/sketch-module-web-view#158]
Hi!
It seems that when switching between themes the value is set to the previous theme value instead of the new value.

I looked into this [code](https://github.com/skpm/sketch-module-web-view/blob/6b42231c0855b97bed9182e1b3e483871ff75c39/lib/set-delegates.js#L38) and I'm might be totally off here, but is it possible that the value should be read from the `change` dictionary instead of `MSTheme.sharedTheme()`?

![sketch theme class](https://user-images.githubusercontent.com/20438532/91657353-fac82180-eac8-11ea-8764-bfdc0ddc6675.gif)

**Comment by mathieudutour** [comment]
What's the change dictionary?

But yeah IIRC you need to restart the plugin for the theme to be picked up (there isn't a listener).

**Comment by yaelsch** [comment]
It seems that there is a change [listener](https://github.com/skpm/sketch-module-web-view/blob/6b42231c0855b97bed9182e1b3e483871ff75c39/lib/set-delegates.js#L252):
```
  NSApplication.sharedApplication().addObserver_forKeyPath_options_context(
    themeObserver,
    'effectiveAppearance',
    NSKeyValueChangeNewKey,
    null
  )
```
And you can see the values are changing without restart, only to the opposite value.

Regarding the change dictionary, if I understand the signature of `observeValueForKeyPath:ofObject:change:context` the "change" parameter is supposed to hold the values of property that changed (see: https://developer.apple.com/documentation/objectivec/nsobject/1416553-observevalueforkeypath)

**Comment by mathieudutour** [comment]
Oh right. Well if you want to have a go at it, I'd be happy to review a PR!
