### ISSUE TITLE
TypeError: _sketchModuleWebView2['default'].clear is not a function.

### ISSUE THREAD

**Issue by bildlich** [skpm/sketch-module-web-view#16]
When inspecting the web view with Safari's web developer tools, the following output appears in the console:

    TypeError: _sketchModuleWebView2['default'].clear is not a function. (In '_sketchModuleWebView2['default'].clear()', '_sketchModuleWebView2['default'].clear' is undefined)

my-command.js looks like this:

    import WebUI from 'sketch-module-web-view'

    export default function (context) {
      const options = {
        identifier: 'unique.id', // to reuse the UI
        x: 0,
        y: 0,
        width: 240,
        height: 180,
        background: NSColor.whiteColor(),
        onlyShowCloseButton: false,
        title: 'My ui 10',
        hideTitleBar: false,
        shouldKeepAround: true,
        frameLoadDelegate: { // https://developer.apple.com/reference/webkit/webframeloaddelegate?language=objc
          'webView:didFinishLoadForFrame:': function (webView, webFrame) {
            context.document.showMessage('UI loaded!')
            WebUI.clear()
          }
        },
        uiDelegate: {}, // https://developer.apple.com/reference/webkit/webuidelegate?language=objc
        onPanelClose: function () {
          // Stuff
        }
      };
      options.handlers = {
        nativeLog: function (s) {
          context.document.showMessage(s)
        }
      };

      const webUI = new WebUI(context, 'test.html', options)
    }

**Comment by mathieudutour** [comment]
it's supposed to be `.clean`. I fixed the readme
