### ISSUE TITLE
Sketch crashes when closing plug-in with web view

### ISSUE THREAD

**Issue by cyberalien** [skpm/sketch-module-web-view#162]
OSX: 11.0.1
Sketch: 69.2 (107504)

When I run any plug-in with a web view, closing window crashes Sketch.

Tested it with basic plug-in created with `skpm create my-plugin-name --template=skpm/with-webview`, it also crashed.

**Comment by programishka** [comment]
When I run any plug-in with a web view, closing window crashes Sketch.  +++

**Comment by ruslan-mir** [comment]
When I run any plug-in with a web view, closing window crashes Sketch. ++++++

**Comment by migenru** [comment]
I have this problem, too. Please, fix

**Comment by mathieudutour** [comment]
are you all on v3.5.0?

**Comment by cyberalien** [comment]
Yes, I'm using 3.5.0. 

Also updated to Sketch 70, issue remains.

**Comment by cyberalien** [comment]
Did some tests.

Plug-in built from default template had version 3.1.something, it crashes. I didn't check version before, assuming dependencies in template would be up to date, but it wasn't.

Updated it to 3.5.0, also crashes.
Downgraded to 3.4.4, it doesn't crash.

My plugin with 3.5.0 crashes.
Downgraded to 3.4.4, it doesn't crash.

So looks like whatever is causing crash exists in 3.1 and 3.5, but not in 3.4.

**Comment by AndreGeng** [comment]
this issue also appears on Catalina on my computer, downgrade sketch-module-web-view to 3.4.4 fix it for me.

**Comment by mathieudutour** [comment]
seems like #161 is the issue - cc @zzzJH

**Comment by zzzJH** [comment]
> seems like #161 is the issue - cc @zzzJH

It seems to be fine on macOS 10.14, but not any higher. 
maybe revert #161 to fix crash.

**Comment by cyberalien** [comment]
Not sure if its related, but there is another issue with web view crashing: https://github.com/skpm/with-webview/issues/25

That one is crashing with version 3.4.4, so it is before #161 . Difference from my setup is user has M1 Mac.

**Comment by elliotdickison** [comment]
Crashing on close for for me with macOS 10.14.6 + Sketch 70.1 + sketch-module-web-view 3.5.0. Error in macOS console is `Sketch XPC connection invalidated`. Pinning sketch-module-web-view to 3.4.4 fixed it for now.
