### ISSUE TITLE
Setting resizeable to "true" crashes the plugin

### ISSUE THREAD

**Issue by ncserny** [skpm/sketch-module-web-view#21]
Any idea why?

**Comment by mathieudutour** [comment]
Hum, works on skpm/sketch-debugger. What's the crash about?

**Comment by ncserny** [comment]
sorry, nevermind. that was actually related to another issue.

**Comment by peerjollux** [comment]
@ncserny: Can you share a bit more about what issue caused the crash? I'm having the same issue after upgrading to the latest version and enabling resizable, but I can't find the what is causing it.
