### ISSUE TITLE
Persistent, togglable webview

### ISSUE THREAD

**Issue by cameronmcefee** [skpm/sketch-module-web-view#26]
Since you're re-thinking how things work in #24 I've got a proposal for you, since I don't believe this is possible in the current version. My panel, and I suspect others are as well, is the kind you want access to multiple times in a design session, with a persistent state. It'd be nice if the webview could be "dismissed" and recalled in the same state without reloading the view. Without knowing what's available via cocoa, my first guess would be to see if you can hide a window without removing it.

For mine, the user flow would look like:

- Hit key command, window pops up
- Do webview stuff
- Hit key command again, window goes away.
- Design, etc.
- Hit key command, window pops up again in same state without reload

**Comment by cameronmcefee** [comment]
I saw in the old codebase when I first looked into it that you've got the webview on a unique thread id so perhaps this was always possible and I just couldn't figure out how it works.

**Comment by mathieudutour** [comment]
in #24, I have a `hide` and `show` method that does pretty much what you describe if I'm not mistaken

**Comment by cameronmcefee** [comment]
Ah nice. Every time I try to suggest improvements you're already ahead of me
