### ISSUE TITLE
Stumped on how to call JS in the plugin from the webview

### ISSUE THREAD

**Issue by comradecid** [skpm/sketch-module-web-view#32]
I'm scratching my head over this, unfortunately. I've successfully...

- Gotten sketch-module-web-view to load a window, driven by a call in my plugin
- Loaded content in the webview using an HTML page
- Established a handler for the action I'd like to trigger when a user performs an action in the webview (such as clicking on a button, etc.)

...the only issue is when it comes down to actually triggering the handler; as noted in great detail in the readme:

On the webview:
----
import pluginCall from 'sketch-module-web-view/client'
pluginCall('nativeLog', 'Called from the webview')

Unfortunately, possibly due to implementation gaps, the import call doesn't work (even when embedding in an external script call marked as 'type="module"'), so any javascript executed in the webview effectively shrugs its shoulders when asked to execute pluginCall().

What might I have missed in my implementation? Any help would be greatly appreciated...

**Comment by mathieudutour** [comment]
I'm not sure what you are doing, it's working fine here: https://github.com/skpm/with-webview/tree/master/template

If you feel like the docs are unclear, feel free to send a PR to improve them :)

**Comment by comradecid** [comment]
ah - thanks... i had no idea that example existed, and the one at skpm/sketch-module-web-view is missing a lot of this detail, so i was having to guess at a lot of details. this helps trememdously :)

also: thanks for all the work you've done on this module... it has been of tremendous value 👍
