### ISSUE TITLE
Create web view with a coordinate not work

### ISSUE THREAD

**Issue by nichenqin** [skpm/sketch-module-web-view#35]
I find that you called `panel.center()` function which overwrite the `x`, `y` property in `options`, does this method called for some particular purpose?

**Comment by mathieudutour** [comment]
I don't think so. There is a completely new API over there: https://github.com/skpm/sketch-module-web-view/pull/24 which I really need to find time to finish...

I think it fixes this

**Comment by nichenqin** [comment]
Will you keep both versions or just merge to `master` branch when new version is landed?

**Comment by mathieudutour** [comment]
I’ll merge it. There are a few bugs in the current version that are hard to fix by design
