### ISSUE TITLE
Update context

### ISSUE THREAD

**Issue by borisdebusscher** [skpm/sketch-module-web-view#36]
When I make a 'pluginCall' from the webview, the context selection in the plugin js file is null. Is there a way to update the current context ? Thanks!

**Comment by mathieudutour** [comment]
No, the context is a static object so once your plugin is called, it won’t change until the plugin is called again. 

But you can use the new API which doesn’t rely on the context:
```js
var sketch = require('sketch')

var selection = sketch.getSelectedDocument().selectedLayers
```

**Comment by borisdebusscher** [comment]
thanks a lot!
