### ISSUE TITLE
Touchbar

### ISSUE THREAD

**Issue by bdebusscher** [skpm/sketch-module-web-view#40]
Does the touchBar feature even work? I don't see anything about electron in your module, you're constructing the browserwindow yourself... Can you give an example for making a new touchbar layout? Thanks!

**Comment by mathieudutour** [comment]
Hum no, is it in the docs? Must have forgotten to remove it

**Comment by borisdebusscher** [comment]
Yes it is! Could you make this possible though ?

**Comment by mathieudutour** [comment]
I’m offline this weekend, can someone send a PR to remove it from the docs?

And I donc think that’s in the scope of this package. It could become a real mess if every plugin start to add action in the touch bar so we need to think carefully about how we want to do this
