### ISSUE TITLE
implementing pluginCall using frameLoadDelegate

### ISSUE THREAD

**Issue by robintindale** [skpm/sketch-module-web-view#41]
Just a quick question to see if I'm missing something. `pluginCall` is currently noted as a "hack", using the changing `window.hash` to signal stuff back up to the plugin, as that's the "only way". I'll outline what I tend to do, and let me know if that's not implemented for a technical reason, or just because it's not been worked on yet :)

The `Webview` already has a frameLoadDelegate https://github.com/skpm/sketch-module-web-view/blob/master/lib/webview-api.js#L47, and this can be used to insert a value into the `windowScriptObject` of the `Webview` every time it loads (using `didClearWindowObject_forFrame`). 

This means you then have a `window.` object in javascript which gives access to an Objective C class and allows you to call chosen methods on it. The class can use `isSelectorExcludedFromWebScript` and `webScriptNameForSelector` to specify which methods. Argument passing works normally but `JSON.stringify`ing everything in the javascript is simplest.

This means calling back to the plugin could be `window.sketchPlugin.callNative(args)` and this will call the relevant Objective C function

**Comment by mathieudutour** [comment]
Hum interesting, didn’t consider that. If you want to send a PR, that sounds def cleaner than what I’m doing.
