### ISSUE TITLE
Options to reset NSWindow corner

### ISSUE THREAD

**Issue by wwsun** [skpm/sketch-module-web-view#47]
Hi, I'm trying to find a way to set the panel corner to `0`, can you provide an option to reset panel corner?

Thanks for your help

**Comment by mathieudutour** [comment]
What do you mean by panel corner? The position?

**Comment by mathieudutour** [comment]
I think we would need to subclass NSWindow entirely to do that.

I don’t want to go in that path, way too thorny. If you really need it, feel free to fork this repo and implement it.

**Comment by wwsun** [comment]
thanks

**Comment by robintindale** [comment]
Shouldn't something like this work in theory https://github.com/electron/electron/issues/414#issuecomment-338393648

I tested it, but `transparent` windows seem to have a nasty black background for me
