### ISSUE TITLE
transparent window has black background

### ISSUE THREAD

**Issue by robintindale** [skpm/sketch-module-web-view#48]
```
let win = new BrowserWindow({ 
  frame: false,
  transparent: true
})
win.show()
``` 
yields

<img src='https://i.imgur.com/GA6SZ0U.png'>

(weird note: this preview appears white background, but clicking on it should show black background)

**Comment by robintindale** [comment]
oh... interesting - it appears white because it's actually transparent? If you change the background color of the github page, the background of the window changes. This suggests the `transparent` is working, but for some reason it's got black underneath it

**Comment by mathieudutour** [comment]
yes if your html have some background color, it will show it. If the background of the html is transparent, it will indeed show a black background for some reason.

**Comment by robintindale** [comment]
the html background thing is slightly strange - even if you set your `html` to be 100px x 100px (with a bigger window), the html background will apply to the whole window
