### ISSUE TITLE
Support or switch to WKWebView

### ISSUE THREAD

**Issue by romannurik** [skpm/sketch-module-web-view#50]
It seems like rendering/scrolling performance with `WKWebView` is better than `WebView` from a preliminary test... it'd be nice to switch over possibly? Don't know if there are ramifications to that, and looking at the APIs it looks like it'd require a bit of a refactor :-/

Related: http://sketchplugins.com/d/763-webview-performance

**Comment by robintindale** [comment]
It looks like `WKWebView` is the officially recommended / supported component, so switching sounds like the right thing to do

> Starting in iOS 8.0 and OS X 10.10, use WKWebView to add web content to your app. Do not use UIWebView or WebView.

**Comment by romannurik** [comment]
FWIW [my fork of this repo](https://github.com/romannurik/sketch-module-wk-web-view) is a first cut at switching to `WKWebView`. Switching may require some API changes though :-/

**Comment by lepetitforgeron** [comment]
does it already work, or is it work in progress?

**Comment by romannurik** [comment]
It works to the extent that I needed for my "Stickers" plugin; there are several events not yet hooked up (you can see in the TODO comments) and IIRC an API change related to executing JS (you can't get the return value of executed JS synchronously with WKWebView AFAICT)

**Comment by mathieudutour** [comment]
actually, I don't mind having an asynchronous API, the electron one is asynchronous as well. The issue is that we need to pass a block and we can't create one in cocoascript for now...

**Comment by romannurik** [comment]
@mathieudutour good point.. FWIW in my fork I don't try to get the return value, I just work around that in the client using manual callbacks (see an example in my Stickers plugin)

**Comment by mathieudutour** [comment]
so in Sketch 51, I added the possibility to create a block: https://github.com/BohemianCoding/SketchAPI/blob/8f3127a66107a8180fce0e13edc90d09afcccdef/Source/dom/components/Document.js#L258-L266

That means that we could get it to work now!

**Comment by mathieudutour** [comment]
I'd love some code review here: #61 :smile:

**Comment by romannurik** [comment]
@mathieudutour awesome!! I can at least offer patching your change locally into my Sketch-Stickers plugin and reporting back :-) I probably won't switch until Sketch 51 is a few months old though, to remain backward compatible.
