### ISSUE TITLE
Const declarations are not supported in strict mode

### ISSUE THREAD

**Issue by rodi01** [skpm/sketch-module-web-view#51]
Since I updated my plugin to the latest version of skpm and sketch-module-web-view, I been getting reports that the plugin doesn't work for some users.

Here is what the console log says:
```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode..
Plugin “commandRenameLayer”, line 432:
» const SuperInit = (0, _runtime.SuperCall)(NSStringFromSelector("init"), [], { type: "@" });
```

I can't reproduce the issue myself but can it be related to the OS/Safari version?

**Comment by robintindale** [comment]
Looks like that line is from https://github.com/darknoon/cocoascript-class/blob/master/src/index.js, so I don't think it is strictly related to this repo

I think I'd file the issue on `skpm` repo, as I believe its supposed to transpile es6 (const) to es5, so something isn't working out right

**Comment by mathieudutour** [comment]
See https://github.com/airbnb/react-sketchapp/issues/106. Can't wait to drop support for El Capitan haha
