### ISSUE TITLE
Strange behaviour, when trying to talk back to webview

### ISSUE THREAD

**Issue by lepetitforgeron** [skpm/sketch-module-web-view#53]
Out of the box, the template is running fine and is succeeding ind sending back the random number via `webContents.executeJavaScript()`.
When I add a new function to my `webview.js`, like
```
window.callMe = function (arg) {
  console.log(`I was called with ${arg}`);
}
```

and call it with `webContents.executeJavaScript('callMe("argument")')`

The call would never reach the function in `webview.js`. 
It seems, that it just works with the example function, included in the template. No added function would be called. Am I missing something in "registering" the function somewhere else?

The other way of communiucation, via `pluginCall()` always works.

**Comment by robintindale** [comment]
That is strange - no there isn't anything additional to do other than assigning the function to the `window` and calling it using `executeJavaScript`.

How different is your code to the template?

Have you ensured that the webview has definitely been reloaded? Sometimes the page contents can be cached until you restart Sketch.

**Comment by lepetitforgeron** [comment]
It doesn't differ at all.
Even uninstalling the plugin from sketch/deleting the build folder, closing sketch, rebuilding the plugin and restarting sketch doesn't do anything good.

changed `my-command.js`
```
  // add a handler for a call from web content's javascript
  webContents.on('nativeLog', (s) => {
    UI.message(s)
    webContents.executeJavaScript('callMe("argument")')
  })
```

added to `webview.js`
```
window.callMe = function (arg) {
  console.log(`I was called with ${arg}`);
}
```
with this code `UI.message(s)` is executed, as this direction of communication always works, but the `console.log(...)` is never touched.

**Comment by robintindale** [comment]
does calling `window.callMe` in `webview.js` itself work?

**Comment by lepetitforgeron** [comment]
No, it doesn't.
Is it normal, that `console.log(window)` doesn't give me anything either? No output at all.

**Comment by lepetitforgeron** [comment]
I have already done the complete deletion and relinking. It doesn't change anything.
I am even unable to inspect the anymore, but it has worked in the past.
I have no idea, what is happening here.

**Comment by robintindale** [comment]
Whether you can inspect or not is usually controlled by `defaults write com.bohemiancoding.sketch3 WebKitDeveloperExtras -bool true` see http://sketchplugins.com/d/665-sketch-49-webview-cannot-be-inspected-element-by-right-click/4

If you're linked up properly, and you've double checked that the file is loading - maybe you can check the `Resources` tab in the `Inspect` window - is the right `javascript` being loaded? Did you check whether the `.html` path is correct

**Comment by lepetitforgeron** [comment]
As I said, inspecting stopped working. IT did work before and the flag didn't change.
 I just wiped Sketch completely from my disk and reinstalled it. Still the same problems.

**Comment by lepetitforgeron** [comment]
I just stumbled across https://github.com/jacopocolo/sketchplugin-webview-template
I am able to inspect the webview created here, without sketch-module-web-view or skpm at all.

**Comment by lepetitforgeron** [comment]
After setting up everything from scratch again (including Sketch itself) it works now.

**Comment by BillQiu** [comment]
> After setting up everything from scratch again (including Sketch itself) it works now.

I have the same problem, how do u solve it ?
After reinstall sketch, init a new project, still dosen't help...
