### ISSUE TITLE
Cannot trigger a new window's `ready-to-show` via the existed window

### ISSUE THREAD

**Issue by wwsun** [skpm/sketch-module-web-view#54]
I want to open window `bw2` via the trigger button in window `bw1`,  however, the following codes cannot trigger the event of `ready-to-show` in `bw2`.

after trigger 'onClickOpenPage2' in `bw1`, the new window shows, but its `ready-to-show` event is not triggered.

```
// bw1.js
import creatBw from './bw2.js';
const bw1 = new BrowserWindow({
  identifier: 'bw-1',
});
bw1.loadURL('page1');
bw1.webContents.on('onClickOpenPage2', () => {
  createBw();
});
```

```
// bw2.js
export default function createBw2() {
  const bw2 = new BrowserWindow({
     identifier: 'bw-2',
  });
  bw2.loadURL('page2');
  bw2.once('ready-to-show', () => {
    // cannot be triggered
    console.log('ready-to-show');
    bw2.show();
    bw2.webContents.executeJavaScript('startApp()');
  })
  return bw2;
}
```

**Comment by mathieudutour** [comment]
it should be `bw.once('ready-to-show', () => {` -> `bw2.once('ready-to-show', () => {`?

**Comment by wwsun** [comment]
yes, it's misspelling, the question still exists? any solutions?

**Comment by mathieudutour** [comment]
can you try sketch-module-web-view@1.1.6?

**Comment by wwsun** [comment]
nice, thanks for your help
