### ISSUE TITLE
focusable option is not working

### ISSUE THREAD

**Issue by JonathanKolnik** [skpm/sketch-module-web-view#55]
v 1.1.6

I am trying to make a browserWindow with the focusable option set to false:
```
const options = {
  identifier: 'unique.id',
  redirectTo: "/list",
  width: 240,
  height: 480,
  show: false,
  focusable: false,
}
let browserWindow = new BrowserWindow(options)
```

However when I run my plugin I get this error in the console:
```
TypeError: panel.setDisableKeyOrMainWindow is not a function. (In 'panel.setDisableKeyOrMainWindow(true)', 'panel.setDisableKeyOrMainWindow' is undefined)
```
which is here in the code https://github.com/skpm/sketch-module-web-view/blob/c525bd8244a213d2f85fef5080c98ebf522f3407/lib/index.js#L119

Some background (in case this can be accomplished in another way)

I am listening to the action "SelectionChanged.finish". Right now that focuses my webview. Ideally I would want it to not focus (because I could have the alwaysOnTop option set to true). This way you can refer to the info in the panel but the sketch window is still focused for use of hotkeys etc. 

I also tried to do browserWindow.blur() at the end of my SelectionChanged handler but that doesn't seem to work either.

Any help would be greatly appreciated!!

**Comment by mathieudutour** [comment]
could you try the version 1.1.7?

**Comment by JonathanKolnik** [comment]
@mathieudutour thank you for looking into it! Unfortunately now I get 

```
TypeError: panel.setCanBecomeKeyWindow is not a function. (In 'panel.setCanBecomeKeyWindow(false)', 'panel.setCanBecomeKeyWindow' is undefined)
```

:(

**Comment by mathieudutour** [comment]
Oh you are right. Unfortunately, it won't possible at the moment: we would need to create a subclass of NSPanel which overrides `canBecomeKeyWindow` and returns a `BOOL`. And for now it's only possible to return an `id` so we are stuck. I removed the `focusable` option from the docs
