### ISSUE TITLE
win.moveTop is not a function

### ISSUE THREAD

**Issue by wwsun** [skpm/sketch-module-web-view#56]
Hi, i want to listen 'openDocument' action to move my panel to front of all application windows, but it seems `win.moveTop()` and `win.focus()` are not work. >> [document](https://github.com/skpm/sketch-module-web-view/blob/master/docs/browser-window.md#winmovetop)

my codes

```
import { getWebview } from 'sketch-module-web-view/remote';

export function onOpenDocument() {
  const mainPanel = getWebview('panel');
  if (mainPanel) {
    mainPanel.moveTop();
  }
}
```

the plugin log prints:
> TypeError: e.moveTop is not a function.

**Comment by mathieudutour** [comment]
should be fixed in version 1.1.7
