### ISSUE TITLE
Usage with Monaco editor

### ISSUE THREAD

**Issue by ryenbeatty** [skpm/sketch-module-web-view#60]
Hi there,

I am currently integrating the [Monaco Editor](https://github.com/Microsoft/monaco-editor) into a webview, and noticed some interesting behaviour.

After the editor is loaded, it's not possible to double click text or drag to select it, which is a feature that is powered by web workers. However, I know that they are working because syntax highlighting is still functioning.

You can reproduce by loading the [Monaco Playgound](https://microsoft.github.io/monaco-editor/playground.html) as the source of a webview, and try to use your mouse to select some text.

This could be related to worker support, but I am wondering if it could also be related to how the webview is constructed. Does that sound plausible?

Any input appreciated,
Ryen

**Comment by mathieudutour** [comment]
I have no idea but there is an error in the console that it cannot find `onMessageFromPlugin` so maybe it's related? I never used Monaco Editor.

**Comment by ryenbeatty** [comment]
Ok, after further investigation I believe it's related to the editor project, thanks for taking a look!
