### ISSUE TITLE
Working example needed for communication between plugin and WebView

### ISSUE THREAD

**Issue by facadev** [skpm/sketch-module-web-view#63]
I read the doc, yet still failed to make the example working. My code is as follows:

src/my-command.js
```
import BrowserWindow from 'sketch-module-web-view'
var sketch = require('sketch')

export default function(context) {
  
  const options = {
    identifier: 'unique.id',
    alwaysOnTop: true
  }
  const browserWindow = new BrowserWindow(options)
  browserWindow.loadURL('./index.htm')

  browserWindow.webContents.on('nativeLog', function(s) {
    context.document.showMessage(s)
    sketch.UI.message(s)
  })
}

```
assets/index.htm
```
<html>
    <body>
        <script type="module">
        import pluginCall from 'sketch-module-web-view/client'
        pluginCall('nativeLog', 'Called from the webview')
        </script>
    </body>
</html>
```

And to debug the WebView, I changed the default setting according to https://github.com/skpm/sketch-module-web-view/blob/master/docs/inspecting-the-webview.md, but it doesn't work –– there's only a "Reload" option in the right-click menu, no "Inspect". (macOS 10.13, Sketch v51.1)

**Comment by facadev** [comment]
Solution:

One should specify the project's resource JS files in package.json to take them in compilation.
```
"resources": [
    "assets/index.js"
  ]
```

**Comment by rodi01** [comment]
@facadev the inspect element works fine for me. One alternative you can do is to go to Safari, make sure develop menu is enabled. 
With your plugin window opened in Sketch go to Safari → Develop → (Your Mac Name) → htmlfilename.
This is how mine looks like:
<img width="667" alt="screen shot 2018-07-24 at 10 46 14 am" src="https://user-images.githubusercontent.com/52461/43156397-dd92b488-8f2e-11e8-9d6c-d0a5c60251ad.png">

I hope this helps.

**Comment by AMoreaux** [comment]
@rodi01 It works like a charm. Thank you 😁
