### ISSUE TITLE
`sendToWebview()` trhows an error:`stringByEvaluatingJavaScriptFromString` is `undefinded`)

### ISSUE THREAD

**Issue by timohofmeijer** [skpm/sketch-module-web-view#66]
`lib/index.js` has –what I believe is an error– in it.
When changing
```
var webView = panel.contentView().subviews()[0]
```
into
```
var subviews = panel.contentView().subviews()
var webView = subviews[subviews.length-1]
```
I got rid of an error (`stringByEvaluatingJavaScriptFromString` undefined) when calling `sendToWebview()`.

**Comment by mathieudutour** [comment]
Do you have a repro? It's working fine in my small example
