### ISSUE TITLE
Open link in default browser

### ISSUE THREAD

**Issue by smlparry** [skpm/sketch-module-web-view#67]
Hey there

Is there anyway we can add a link from within the webview that opens in the users default browser? 

I have tried
`<a href="https://google.com>Google</a>` which navigates the webview to google (expected)
and
`a href="https://google.com" target="_blank">Google</a>` which seems to do nothing

Is this possible?

**Comment by tborychowski** [comment]
I found a workaround: https://sketchplugins.com/d/354-open-link-in-web-browser
Basically you intercept all clicks on links in the webview, then pass the url in a postMessage to the host and in the host you execute this:
```c
  NSWorkspace.sharedWorkspace().openURL(NSURL.URLWithString("http://some-website.com"));
```

**Comment by mathieudutour** [comment]
I'd do something like this indeed:

- on the webview:
  ```js
  function interceptClickEvent({ target }) {
    if (target.tagName === 'A' && target.getAttribute('target') === '_blank') {
      e.preventDefault();
      window.postMessage('externalLinkClicked', target.getAttribute('href'))
    }
  }

  // listen for link click events at the document level
  document.addEventListener('click', interceptClickEvent);
  ```

- on the plugin:
  ```js
  webview.webContent.on('externalLinkClicked', href => {
    NSWorkspace.sharedWorkspace().openURL(NSURL.URLWithString(href))
  })
  ```

That'd be something worth putting in the doc if someone wants to send a PR

**Comment by tborychowski** [comment]
⬆️ added :-)
