### ISSUE TITLE
Displaying Layer assets from Sketch to Webview, and rendering in WebView

### ISSUE THREAD

**Issue by Mathieu-Gosbee-ConnectedLab** [skpm/sketch-module-web-view#74]
As the title suggests, I'm looking to display assets from a Layer, and rendering them in a special way via my WebView. Is there a way to access Sketch items (exported to an image format, likely) and display them in a Webview?

**Comment by robintindale** [comment]
There's no special route, you would need to 

* use API in Sketch to export the layers to images on the local file system https://developer.sketchapp.com/reference/api/#export
* send the image file path over to the webview
* in the webview, display the images using `file://` URLs

**Comment by mathieudutour** [comment]
Indeed, nothing special here

**Comment by robintindale** [comment]
Does using `output: false` in the new export API work? If not, I'd post in the Sketch API repo https://github.com/sketch-hq/SketchAPI/issues

**Comment by nuthinking** [comment]
@robintindale It works, but it returns data in the command. How do I pass it then to the web view? Unlike Figma, command and web view can only communicate via strings, AFAIK.
