### ISSUE TITLE
PreventDefault on Close event stops function

### ISSUE THREAD

**Issue by peerjollux** [skpm/sketch-module-web-view#80]
When using ` event.preventDefault()` or after touching the `event` variable within in the Close event, it stops running.

For example:
```javascript
browserWindow.on("close", function() {
    console.log("This does show up");
    event.preventDefault()
    console.log("This does NOT show up");
})
```
or:
```javascript
browserWindow.on("close", function() {
    console.log("This does show up");
    const test = event;
    console.log("This does NOT show up");
})
```

Any idea how to solve this? Thanks

**Comment by robintindale** [comment]
is `event` actually defined? maybe it's just silently crashing

**Comment by mathieudutour** [comment]
That's the issue I think yes. Debugging delegate is a bit of a pain because it doesn't show anything.

Maybe we should wrap the handler in a `try/catch` by default 🤔 Would there be any unwanted side effects?

**Comment by peerjollux** [comment]
> is `event` actually defined? maybe it's just silently crashing

You are right, I didn't set event as param. I've tried to set is as param before and console.log it but this was crashing Sketch. That's why I unset it. 

I just found out it was actually sketch-dev-tools that was crashing

**Comment by peerjollux** [comment]
I'm using the following code now. Now it does not stop the the function, but it also does not close the window. Any idea why?

```javascript
  browserWindow.on("close", event => {
    event.preventDefault();
    console.log('this does show up');
  });
```

**Comment by nadavkaner** [comment]
I can't find a way to prevent from the window to close
I tried doing this 
```
browserWindow.on("close", event => {
    event.preventDefault();
  });
```
But the window is still closed

**Comment by mathieudutour** [comment]
closing in favour of #136
