### ISSUE TITLE
Cannot use WebContents.emit

### ISSUE THREAD

**Issue by g6ling** [skpm/sketch-module-web-view#83]
https://github.com/skpm/sketch-module-web-view/blob/099fe8cb3d3685606c93e0c9009954def992f89e/lib/set-delegates.js#L241

I think this line need to be changed like `browserWindow.webContents.emit(...arguments)`.

When i use postMessage
```
window.postMessage('nativeLog', 'Called from the webview')
```
like this, the argument is array(? NS_Array?). So, I think using spread is correct. 

Maybe other argument has same problem.

**Comment by mathieudutour** [comment]
you are right 2.1.4 should fix it
