### ISSUE TITLE
2.1.3 update breaks events

### ISSUE THREAD

**Issue by cyberalien** [skpm/sketch-module-web-view#84]
Events are broken in 2.1.3. postMessage does not work. Even basic instructions from demo result in plugin that does not do anything.

Steps to reproduce:

1. Build basic plugin:
```
skpm create test-sketch-webview --template=skpm/with-webview
```
2. Open it in Sketch.
3. Click menu.
Nothing happens. No error messages, no output.

However when after downgrading to 2.1.2:
```
npm install sketch-module-web-view@2.1.2
npm run build
```
and it works again.

**Comment by mathieudutour** [comment]
you are right 2.1.4 should fix it
