### ISSUE TITLE
`webView.url()` throw error `e.url` is undefined

### ISSUE THREAD

**Issue by lijinpengFj** [skpm/sketch-module-web-view#85]
system: macOS Mojave v10.14.2
sketch: v52.2

hi, js code has error `'e.url' is undefined`, i use Safari to get it when i'm debugging, it maybe a problem.
I think `set-delegates.js` is the code which throw the error.
https://github.com/skpm/sketch-module-web-view/blob/master/lib/set-delegates.js#L101

Here is the error info, and i'm so sorry for i don't know how to format the error info :(
![image](https://user-images.githubusercontent.com/10599551/52997881-b7fda600-345c-11e9-88ac-7d68f402d2ce.png)

`
[Error] TypeError: e.url is not a function. (In 'e.url()', 'e.url' is undefined)
	webView:didCommitNavigation: (/Users/jinpeng/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Anto.sketchplugin/Contents/Sketch/index.js:1012:1391)
	JSObjectCallAsFunction
	__MOGetBlockForJavaScriptFunction_block_invoke
	WebKit::NavigationState::NavigationClient::didCommitNavigation(WebKit::WebPageProxy&, API::Navigation*, API::Object*)
	WebKit::WebPageProxy::didCommitLoadForFrame(unsigned long long, unsigned long long, WTF::String const&, bool, unsigned int, WebCore::CertificateInfo const&, bool, std::optional<WebCore::HasInsecureContent>, WebKit::UserData const&)
	void IPC::callMemberFunctionImpl<WebKit::WebPageProxy, void (WebKit::WebPageProxy::*)(unsigned long long, unsigned long long, WTF::String const&, bool, unsigned int, WebCore::CertificateInfo const&, bool, std::optional<WebCore::HasInsecureContent>, WebKit::UserData const&), std::__1::tuple<unsigned long long, unsigned long long, WTF::String, bool, unsigned int, WebCore::CertificateInfo, bool, std::optional<WebCore::HasInsecureContent>, WebKit::UserData>, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul>(WebKit::WebPageProxy*, void (WebKit::WebPageProxy::*)(unsigned long long, unsigned long long, WTF::String const&, bool, unsigned int, WebCore::CertificateInfo const&, bool, std::optional<WebCore::HasInsecureContent>, WebKit::UserData const&), std::__1::tuple<unsigned long long, unsigned long long, WTF::String, bool, unsigned int, WebCore::CertificateInfo, bool, std::optional<WebCore::HasInsecureContent>, WebKit::UserData>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul>)
	void IPC::handleMessage<Messages::WebPageProxy::DidCommitLoadForFrame, WebKit::WebPageProxy, void (WebKit::WebPageProxy::*)(unsigned long long, unsigned long long, WTF::String const&, bool, unsigned int, WebCore::CertificateInfo const&, bool, std::optional<WebCore::HasInsecureContent>, WebKit::UserData const&)>(IPC::Decoder&, WebKit::WebPageProxy*, void (WebKit::WebPageProxy::*)(unsigned long long, unsigned long long, WTF::String const&, bool, unsigned int, WebCore::CertificateInfo const&, bool, std::optional<WebCore::HasInsecureContent>, WebKit::UserData const&))
	IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)
	WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
	IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)
	IPC::Connection::dispatchIncomingMessages()
	WTF::RunLoop::performWork()
	WTF::RunLoop::performWork(void*)
	__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
	__CFRunLoopDoSource0
	__CFRunLoopDoSources0
	__CFRunLoopRun
	CFRunLoopRunSpecific
	RunCurrentEventLoopInMode
	ReceiveNextEventCommon
	_BlockUntilNextEventMatchingListInModeWithFilter
	_DPSNextEvent
	-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
	-[NSApplication run]
	NSApplicationMain
	start
`

**Comment by lijinpengFj** [comment]
add some info, `sketch-module-web-view` verson 2.1.4

**Comment by mathieudutour** [comment]
should be fixed in 2.1.5
