### ISSUE TITLE
Correct way of passing state to React in a webview

### ISSUE THREAD

**Issue by jan-dh** [skpm/sketch-module-web-view#86]
I was wondering what the best way would be to pass data from my plugin to the webview. In the webview I have a React application and I need to set the state of that application with data coming from Sketch.

The React application starts when I run the plugin. I then run this:

```
// Pass the state to the window
  webContents.on('did-finish-load', () => {
    // Hardcoded test-data
    const state = {
      colors:[{name:'red-dark', hex:'#9B0316' }, { name:'red', hex:'#D0021B', }, { name:'pink', hex:'#FF61D9' }, { name:'orange', hex:'#ff8600' }],
      fontFamilies:{'Pro Sans':'pro-sans', 'Addelle':'addelle' },
      fontSizes:{6:'', 8:'', 10:'', 12:'', 14:'', 16:'', 20:'', 22:'', 24:'', 26:'', 28:''},
    }
    webContents
      .executeJavaScript(
       `setInitialState(${JSON.stringify(state)})`
      )
      .then(res => {
       sketch.UI.message('State set');
      })
  })
```

I set the render function up so I can access the React application from the window like so (based on this [article](https://brettdewoody.com/accessing-component-methods-and-state-from-outside-react/)):

```
render(<App ref={(appComponent) => {window.appComponent = appComponent}} />, document.getElementById("main"));
```

Now I should be able to set the initial state like this:

```
 window.appComponent.loadInitialState(JSON.parse(state));
```

This works when I run the application outside of Sketch. I can simple set the state from the window:

```
 const state = {
      colors:[{name:'red-dark', hex:'#9B0316' }, { name:'red', hex:'#D0021B', }, { name:'pink', hex:'#FF61D9' }, { name:'orange', hex:'#ff8600' }],
      fontFamilies:{'Pro Sans':'pro-sans', 'Addelle':'addelle' },
      fontSizes:{6:'', 8:'', 10:'', 12:'', 14:'', 16:'', 20:'', 22:'', 24:'', 26:'', 28:''},
    }

 window.appComponent.loadInitialState(state);
```

However, when I try this approach with skpm, Sketch keeps crashing. I can't get any info from the logs. 
I tried calling this from within `webview.js`: 

```
// Set initial state
window.setInitialState = function (state) {
 // This should work - but it doesn't
 // window.appComponent.loadInitialState(JSON.parse(state));
}
```

[This](https://github.com/jan-dh/sketch-tailwind/tree/webview) is the repo. I've studied the example from the `sketch-dev-tools` but that examples uses redux. So 2 questions:

1.  Is anyone able to debug my example? I can't get any further then Sketch crashing, and can't inspect my webview (I tried the dev setup from the docs, I'm not able to inspect). 

2. Is there a better, more preferable way to pass an initial state from Sketch to a React application. I don't need Redux in my application and a simple implementation of passing data to React would be perfect.

**Setup**
* Mojave 10.14.3.
* Sketch 53.2

**Comment by mathieudutour** [comment]
Not sure what is happening with your app but you don't need redux to use the setup from `sketch-dev-tool`:
- load the URL
- insert JS (which will be loaded before the react app)
- in your react app, check for the value of the global you set in the previous step, that's your initial step

https://github.com/skpm/sketch-dev-tools/blob/master/src/show-debugger.js#L62-L64
https://github.com/skpm/sketch-dev-tools/blob/3205f2f844354eb374932f75f0ef82d6556f8293/resources/app/redux/ducks/settings.js#L4

**Comment by robintindale** [comment]
I think the problem is running `JSON.parse` on the passed state. Even though you used `JSON.stringify`, you won't need to parse it on the webview end, as the `executeJavascript` is a string itself.

**Comment by jan-dh** [comment]
@mathieudutour thanks for pointing me in the right direction. Got it working now with `insertJS`. 
@robintindale tried your solution, even with removing the parse, it still crashed. Got it working now, thanks for the help!
