### ISSUE TITLE
Titlebar color

### ISSUE THREAD

**Issue by DrinkingWords** [skpm/sketch-module-web-view#88]
Is there any way to have the same color of titlebar whether the window is focused or not?
Is there any way to move the window without titlebar?

**Comment by mathieudutour** [comment]
> Is there any way to have the same color of titlebar whether the window is focused or not?

You could add the titlebar and draw it yourself in your html

> Is there any way to move the window without titlebar?

Yes, see https://github.com/skpm/sketch-module-web-view/blob/master/docs/frameless-window.md#draggable-region
