### ISSUE TITLE
Workflow for using React

### ISSUE THREAD

**Issue by amin-nas** [skpm/sketch-module-web-view#9]
Hi there,

I'm trying out skpm with react, and I'm not sure if I'm going about it the right way. Listing the steps I followed below. Appreciate any feedback.

1. Run `skpm init` and follow the setup
2. Add react `npm install --save react react-dom`
3. Add web view module for sketch `npm i -S sketch-module-web-view`
4. Add a command that creates the web view. Code [here](https://github.com/amin-nas/Sketch-to-Clickthrough-HTML/blob/1.3_switch_to_skpm/src/my-command.js)
5. In the Resources folder, create the react component that will be included in the web view. Code [here](https://github.com/amin-nas/Sketch-to-Clickthrough-HTML/blob/1.3_switch_to_skpm/Resources/hello.js)

I couldn't figure out how/where to include the react component in the webview. So I manually added a HTML file in the plugin's Resources folder. Code [here](https://github.com/amin-nas/Sketch-to-Clickthrough-HTML/blob/1.3_switch_to_skpm/plugin.sketchplugin/Contents/Resources/hello.html)

**Comment by mathieudutour** [comment]
Yeah that's how I do it as well. Any insights on how to make it more streamlined?

**Comment by amin-nas** [comment]
I was hoping to use react-router and have a single entry point instead of adding those HTML files in the Resources folder. But no luck so far.

**Comment by timohofmeijer** [comment]
@amin-nas I personally develop the UI as a separate (Vue) project. During development I point the webView to my local dev server (possible since yesterday : ). This way I have changes to my UI auto reload right within Sketch. For production I build the UI in the Resource directory and switch back to loading it as a html file. Feels really smooth.

**Comment by amin-nas** [comment]
Much better workflow! Thanks for sharing.

**Comment by BearRan** [comment]
> @amin-nas I personally develop the UI as a separate (Vue) project. During development I point the webView to my local dev server (possible since yesterday : ). This way I have changes to my UI auto reload right within Sketch. For production I build the UI in the Resource directory and switch back to loading it as a html file. Feels really smooth.

It a great solution! Thank you!

**Comment by BearRan** [comment]
> @amin-nas I personally develop the UI as a separate (Vue) project. During development I point the webView to my local dev server (possible since yesterday : ). This way I have changes to my UI auto reload right within Sketch. For production I build the UI in the Resource directory and switch back to loading it as a html file. Feels really smooth.

It's a great solution! Thank you!
