### ISSUE TITLE
"Not allowed to load local resource" when trying to import an asset js file

### ISSUE THREAD

**Issue by dploeger** [skpm/sketch-module-web-view#90]
On Sketch 53.2 with sketch-module-web-view version 2.1.6:

When I create a local asset html file to load in the web view, which sources an asset JS file as well, the webview refuses to load that JS file with the error message "Not allowed to load local resource".

As a reference example you can use [the 2.0 branch of my units plugin](https://github.com/dploeger/sketch-plugin-units/tree/2.0.0) and call Units/Settings from the Plugins menu, then in the webview open up the inspector by right-clicking and selecting "inspect element".

[This issue](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/158) refers to Webview not loading any file resources anymore and a convertFileSrc method for converting those sources to localhost urls.

Am I just doing that wrong or misunderstanding the process or how can this be achieved?

**Comment by mathieudutour** [comment]
once again, I'm pretty sure it's a mistake with how you setup your plugin. Have a look here: https://github.com/skpm/with-webview/tree/master/template and you will see that you are missing a bunch of stuff

**Comment by dploeger** [comment]
Ohh! I didn't know, there was a template for webview. I'll check, thanks.

**Comment by dploeger** [comment]
Okay, got the problem. Interestingly enough, it was just the src-path, which I got wrong.

I used:
```
    <script type="text/JavaScript" src="js/settings-view.js"></script>
```

while the correct form is

```
    <script type="text/JavaScript" src="../js/settings-view.js"></script>
```

So a completely misleading error message in the inspector sadly.

Thanks for the support.
