### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by peerjollux** [skpm/sketch-module-web-view#91]
This might be the wrong place to ask this question, but because it's a bit outside my field of expertise I'm going ask it anyway. Feel free to tell me if this is the wrong place ;)

I just updated from version `1.0.2` to the latest version and now I'm having issues with an api call. 

I'm getting the following error
```
[Error] Preflight response is not successful
[Error] Fetch API cannot load https://api.gumroad.com/v2/licenses/verify due to access control checks.
[Error] Failed to load resource: Preflight response is not successful (verify, line 0)
```

By using the following code:
```
export const verifyLicense = ({ productPermalink, licenseKey }) => {
  let apiUrl = "https://api.gumroad.com/v2/licenses/verify";

  const options = {
    method: "POST",
    headers: {
      "Access-Control-Allow-Methods": "POST",
      Accept: "application/json",
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*"
    },
    body: JSON.stringify({
      product_permalink: productPermalink,
      license_key: licenseKey,
      increment_uses_count: false
    })
  };

  return fetch(apiUrl, options);
};
```

Do you have any idea how to solve this?

**Comment by mathieudutour** [comment]
CORS is a server issue: if the server doesn't want to receive requests from other domains, that's what's happening.

I'm not sure how it could be linked to updating the webview 🤔

**Comment by peerjollux** [comment]
It indeed is, but I do think the problem is related to update.

In the latest version the request header for origin is null. Before this was file://.
I did a quick research I think it's related to WKWebView. I'll try to investigate it more and find a solution for it
