### ISSUE TITLE
`vibrancy` doesn't appear to be working

### ISSUE THREAD

**Issue by huw** [skpm/sketch-module-web-view#94]
I've been trying to get my window to launch with a vibrancy effect, but to no avail. Here's my code:

```js
import BrowserWindow from 'sketch-module-web-view';

export const onStartup = async () => {
  const browserWindow = new BrowserWindow({
    width: 680,
    height: 368,
    show: false,
    titleBarStyle: 'hidden',
    vibrancy: 'light',
  });

  NSThread.mainThread().threadDictionary().browserWindow = browserWindow;
};

export default () => {
  const { browserWindow } = NSThread.mainThread().threadDictionary();
  if (browserWindow) {
      browserWindow.show();
  }
};
```

And here's what I get when I run it:

<img width="1303" alt="Screen Shot 2019-04-02 at 5 58 34 pm" src="https://user-images.githubusercontent.com/2456132/55382503-860a5400-5571-11e9-90f8-dbb8949c0590.png">

I also tried the same with `frame: false`, but nothing. Am I maybe misunderstanding how to use this, or what I should expect it to do?

**Comment by mathieudutour** [comment]
should be fixed in 3.0.1
