### ISSUE TITLE
`isWebviewPresent` not working with `vibrancy`

### ISSUE THREAD

**Issue by kyotoMike** [skpm/sketch-module-web-view#96]
When any `vibrancy` is set, `isWebviewPresent` can no longer find the browser window in the thread dictionary. Same goes for `sendToWebview` and `BrowserWindow.fromId`.

When commenting out the part where the `effectView` [is added](https://github.com/skpm/sketch-module-web-view/blob/3167fe15823e6e3b8019bbaf39e44774a619c4f3/lib/browser-api.js#L532) to the `panel.contentView()`, the browser window can be accessed just fine.

**Comment by mathieudutour** [comment]
should be fixed in v3.0.2
